<?php
header("Content-Type: application/json");
// Enable error reporting for debugging
ini_set('display_errors', 1);
error_reporting(E_ALL);
$action = isset($_POST['action']) ? $_POST['action'] : '';
$debug = isset($_POST['debug']) ? $_POST['debug'] : false;

if($debug){
    include("./functions_DEBUG.php");
}else{
    include("./functions.php");
}

if(isset($action)){
    switch ($action) {
        case 'receiptType':
            
            $receiptType = isset($_POST['receiptType']) ? $_POST['receiptType'] : '';


            switch ($receiptType) {
                case 'sales_c':
                    // $escposContent = "GyEbQVdlYjJGaXggLSBERU1PClN0dXJlbmthdHUgMjYKMDA1MTAgSGVsc2lua2kKVGVsLjogMDEyMzQ1NgpPUkcuTlI6IDIzODUzNjEyChtAChskG0FTQVZFIFJFQ0VJUFQsIENVU1RPTUVSJ1MgQ09QWQobQBsmG0AbQBtCG0AbQhtAG0IbQFRFUk1JTkFMOhtCMjNDTktSNTA4NjgwChtATUVSQ0hBTlQ6G0I2NTg1NzE1MyA0MzY0NTI5NAobQENBU0hJRVI6G0IxMjM0NTYKG0BEQVRFOjIwMjQtMTEtMTgbQlRJTUU6MTM6MzUKG0AKGyYbQRtSU0FMRQpBUFBST1ZFRAobUBtAChtSG0EbQRtQGyYbQEFNT1VOVBtCRVVSIDMuMzYKG0AbQhtAG1JUT1RBTFtCRVVSIDMuMzYKG1AbQAobQBtCG0AbQhtSG0AbQhtAG0IbUBtBG0AbQBsmVklTQSBDT05UQUNUTEVTUwpWSVNBIERlQkJpdAobAKioqKioqKioqNjEwNxtCUFNOOiAwMgobQAobQRtAG0EbQBsmG0FXTE4gSy8xIDMgMDAwIFdMTiAwMDggMzcyMDE3ChtAUkVDRUlQVDowMDAwMzcbQlJFRjozMDgwMjQyNTQwMTUKG0AKGyZBVEM6MDQxQyAKQUlEOkEwMDAwMDAwMDMxMDEwClRWUjowMDAwMDAwMDAwClRTSTowMDAwCkFSUUM6QzVBMjJCMjBBREY2MjUwNwoKGyc=";
                    // customer copy Finnish
                    $escposContent = "GyEbUBtBV2ViMkZpeCAtIERFTU8KU3R1cmVua2F0dSAyNgowMDUxMCBIZWxzaW5raQpQdWg6IDAxMjM0NTYKWS10dW5udXM6IDIzODUzNjEyCgobJhtQG0BQxMRURTobQjI0MTUyNzMzMzAxMTEwMTA1NTgzMjg1MgobQExJSUtFOhtCMTIzNDU2IDY1ODU3MTUzChtAUFZNOjIwMjUtMDMtMDMbQkFJS0E6MTg6MTgKG0AbQQobUk9TVE8KSFlWxEtTWVRUWQobUAobQFNVTU1BG0JFVVIgMTUsMjUKG0AbUllIVEVFTlPEG0JFVVIgMTUsMjUKG0AbUApWaXNhIENyZWRpdApQSU4gS09PREkKKioqKioqKioqKioqMjk3NRtCUFNOOjAxChtAChtBU0FNIENhMSAzIDAwMCBEVU0gMDQ3IDc3ODU5MAobQEtVSVRUSTowMDEzODgbQlJFRjozMDgxNTY2NTQ0MzAKG0AKQVRDOjAwMTUzICBBRUQ6MTkxMjAxG0JBUkM6MDAKG0BBSUQ6QTAwMDAwMDAwMzEwMTAKVFZSOjA4QzAwMDgwMDAKVFNJOkU4MDAKVEM6Mjk3MEU3QjMzMTYzNDlBQwoKGyQbUBtBU8RJTFlUxCBLVUlUVEksIEFTSUFLS0FBTiBLQVBQQUxFCgobJwAA";
                break;
                case 'sales_m':
                        // merchant copy English
                    $escposContent = "GyEbUBtBV2ViMkZpeCAtIERFTU8KU3R1cmVua2F0dSAyNgowMDUxMCBIZWxzaW5raQpUZWwuOiAwMTIzNDU2Ck9SRy5OUjogMjM4NTM2MTIKChsmG1AbQFRFUk1JTkFMOhtCMjQxNTI3MzMzMDExMTAxMDU1ODMyODUyChtATUVSQ0hBTlQ6G0IxMjM0NTYgNjU4NTcxNTMKG0BEQVRFOjIwMjUtMDMtMDMbQlRJTUU6MTg6MTgKG0AbQQobUlNBTEUKQVBQUk9WRUQKG1AKG0BBTU9VTlQbQkVVUiAxNSwyNQobQBtSVE9UQUwbQkVVUiAxNSwyNQobQBtQClZpc2EgQ3JlZGl0ClBFUlNPTkFMIENPREUKKioqKioqKioqKioqMjk3NRtCUFNOOjAxChtAChtBU0FNIENhMSAzIDAwMCBEVU0gMDQ3IDc3ODU5MAobQFJFQ0VJUFQ6MDAxMzg4G0JSRUY6MzA4MTU2NjU0NDMwChtACkFUQzowMDE1MyAgQUVEOjE5MTIwMRtCQVJDOjAwChtAQUlEOkEwMDAwMDAwMDMxMDEwClRWUjowOEMwMDA4MDAwClRTSTpFODAwClRDOjI5NzBFN0IzMzE2MzQ5QUMKChskG1AbQVNBVkUgUkVDRUlQVCwgTUVSQ0hBTlQnUyBDT1BZCgobJwAA";
                break;
                case 'refund_c':
                    // Customer copy Finnish
                    $escposContent = "GyEbUBtBV2ViMkZpeCAtIERFTU8KU3R1cmVua2F0dSAyNgowMDUxMCBIZWxzaW5raQpQdWg6IDAxMjM0NTYKWS10dW5udXM6IDIzODUzNjEyCgobJhtQG0BQxMRURTobQjI0MTUyNzMzMzAxMTEwMTA1NTgzMjg1MgobQExJSUtFOhtCMTIzNDU2IDY1ODU3MTUzChtAUFZNOjIwMjUtMDMtMDMbQkFJS0E6MTg6MjMKG0AbQQobUkhZVklUWVMKSFlWxEtTWVRUWQobUAobQFNVTU1BG0JFVVIgMTUsMjUKG0AbUllIVEVFTlPEG0JFVVIgMTUsMjUKG0AbUApWaXNhIENyZWRpdAoqKioqKioqKioqKioyOTc1G0JQU046MDEKG0AKG0FIWVbES1NZTiBUxFTEIEtPUlRUSUEgSFlWSVRFVFTEVsROIFlMTMQgRVJJVEVMTFlOIFNVTU1BThtACgpNeXlq5G4gYWxsZWtpcmpvaXR1czogCgobcV8KTXl5auRuIG5pbWk6IAoKG3FfCgobQVNBTSBDLTEgMyAwMDAgRFVNIDA0NyAyNzQ0NDcKG0BLVUlUVEk6MDAxMzg5G0JSRUY6MzA4MTU2NjYxMTY3ChtACkFUQzowMDE1NCAgQUVEOjE5MTIwMRtCQVJDOloxChtAQUlEOkEwMDAwMDAwMDMxMDEwClRWUjowMDAwMDAwMDAwClRTSToyMDAwCkFBQzpCOUM2RUVBOEQ3RDI2Q0VECgobJBtQG0FTxElMWVTEIEtVSVRUSSwgQVNJQUtLQUFOIEtBUFBBTEUKChsn";
                break;
                case 'refund_m':
                        // merchant copy ENG
                    $escposContent = "GyEbUBtBV2ViMkZpeCAtIERFTU8KU3R1cmVua2F0dSAyNgowMDUxMCBIZWxzaW5raQpUZWwuOiAwMTIzNDU2Ck9SRy5OUjogMjM4NTM2MTIKChsmG1AbQFRFUk1JTkFMOhtCMjQxNTI3MzMzMDExMTAxMDU1ODMyODUyChtATUVSQ0hBTlQ6G0IxMjM0NTYgNjU4NTcxNTMKG0BEQVRFOjIwMjUtMDMtMDMbQlRJTUU6MTg6MjMKG0AbQQobUlJFRlVORApBUFBST1ZFRAobUAobQEFNT1VOVBtCRVVSIDE1LDI1ChtAG1JUT1RBTBtCRVVSIDE1LDI1ChtAG1AKVmlzYSBDcmVkaXQKKioqKioqKioqKioqMjk3NRtCUFNOOjAxChtAChtBU0FNIEMtMSAzIDAwMCBEVU0gMDQ3IDI3NDQ0NwobQFJFQ0VJUFQ6MDAxMzg5G0JSRUY6MzA4MTU2NjYxMTY3ChtACkFUQzowMDE1NCAgQUVEOjE5MTIwMRtCQVJDOloxChtAQUlEOkEwMDAwMDAwMDMxMDEwClRWUjowMDAwMDAwMDAwClRTSToyMDAwCkFBQzpCOUM2RUVBOEQ3RDI2Q0VECgobJBtQG0FTQVZFIFJFQ0VJUFQsIE1FUkNIQU5UJ1MgQ09QWQoKGycA";
                break;
                case 'reversal_c':
                    $escposContent = "GyEbUBtBV2ViMkZpeCAtIERFTU8KU3R1cmVua2F0dSAyNgowMDUxMCBIZWxzaW5raQpQdWg6IDAxMjM0NTYKWS10dW5udXM6IDIzODUzNjEyCgobJhtQG0BQxMRURTobQjI0MTUyNzMzMzAxMTEwMTA1NTgzMjg1MgobQExJSUtFOhtCMTIzNDU2IDY1ODU3MTUzChtAUFZNOjIwMjUtMDMtMDMbQkFJS0E6MTg6MTgKG0AbQQobUk9TVE8KS1VNT1RUVQobUAobQFNVTU1BG0JFVVIgMTUsMjUKG0AbUllIVEVFTlPEG0JFVVIgMTUsMjUKG0AbUApWaXNhIENyZWRpdApQSU4gS09PREkKKioqKioqKioqKioqMjk3NRtCUFNOOjAxChtAChtBU0FNIENhMSAzIDAwMCBEVU0gMDQ3IDc3ODU5MAobQEtVSVRUSTowMDEzODgbQlJFRjozMDgxNTY2NTQ0MzAKG0AKQVRDOjAwMTUzICBBRUQ6MTkxMjAxG0JBUkM6MDAKG0BBSUQ6QTAwMDAwMDAwMzEwMTAKVFZSOjA4QzAwMDgwMDAKVFNJOkU4MDAKVEM6Mjk3MEU3QjMzMTYzNDlBQwoKGyQbUBtBU8RJTFlUxCBLVUlUVEksIEFTSUFLS0FBTiBLQVBQQUxFCgobJwAA";
                break;
                case 'reversal_m':
                    $escposContent = "GyEbUBtBV2ViMkZpeCAtIERFTU8KU3R1cmVua2F0dSAyNgowMDUxMCBIZWxzaW5raQpUZWwuOiAwMTIzNDU2Ck9SRy5OUjogMjM4NTM2MTIKChsmG1AbQFRFUk1JTkFMOhtCMjQxNTI3MzMzMDExMTAxMDU1ODMyODUyChtATUVSQ0hBTlQ6G0IxMjM0NTYgNjU4NTcxNTMKG0BEQVRFOjIwMjUtMDMtMDMbQlRJTUU6MTg6MTgKG0AbQQobUlNBTEUKQ0FOQ0VMTEVEChtQChtAQU1PVU5UG0JFVVIgMTUsMjUKG0AbUlRPVEFMG0JFVVIgMTUsMjUKG0AbUApWaXNhIENyZWRpdApQRVJTT05BTCBDT0RFCioqKioqKioqKioqKjI5NzUbQlBTTjowMQobQAobQVNBTSBDYTEgMyAwMDAgRFVNIDA0NyA3Nzg1OTAKG0BSRUNFSVBUOjAwMTM4OBtCUkVGOjMwODE1NjY1NDQzMAobQApBVEM6MDAxNTMgIEFFRDoxOTEyMDEbQkFSQzowMAobQEFJRDpBMDAwMDAwMDAzMTAxMApUVlI6MDhDMDAwODAwMApUU0k6RTgwMApUQzoyOTcwRTdCMzMxNjM0OUFDCgobJBtQG0FTQVZFIFJFQ0VJUFQsIE1FUkNIQU5UJ1MgQ09QWQoKGycA";
                break;
                case 'capture':
                    $escposContent = "GyEbUBtBV2ViMkZpeCAtIERFTU8KU3R1cmVua2F0dSAyNgowMDUxMCBIZWxzaW5raQpUZWwuOiAwMTIzNDU2Ck9SRy5OUjogMjM4NTM2MTIKChsmG1AbQVNFVFRMRU1FTlQKChtAU0FNIApGUk9NOhtCMjAyNS0wMy0wMiAxMTo1NAobQFRPOhtCMjAyNS0wMy0wMyAxODoxMAobQEJBVENIOhtCMDQ2ChtAVEVSTUlOQUw6G0IyNDE1MjczMzMwMTExMDEwNTU4MzI4NTIKG0BNRVJDSEFOVDobQjEyMzQ1NiA2NTg1NzE1MwobQAobQRtSG3BORVQgVE9UQUxTChtwG1IbQFZpc2EbUApTQUxFG0EyG0JFVVIgNCw5MAobQBtSU1VNG0EyG0JFVVIgNCw5MAobQBtQG0EbcBtSG0BUT1RBTAobUFNBTEUbQTIbQkVVUiA0LDkwChtAG1JTVU0bQTIbQkVVUiA0LDkwChtAChtQG0FFTkQKChskGycA";
                break;
                default:
                    $escposContent = "";
            }

            echo json_encode(["escposContent" => $escposContent]);
            exit;

        break;
        case 'decodeReceipt':
            $encodedReceipt = isset($_POST['encodedReceipt']) ? $_POST['encodedReceipt'] : '';
            $decoded_receipt = ReceiptDecoder::decodeAndDisplayReceipt($encodedReceipt);
            // print_r($decoded_data_array);
            // print_r(json_encode($decoded_data_array, JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT));
            // print_r($decoded_receipt);
            exit($decoded_receipt);
        
        break;
    }            
}
echo json_encode(["error" => "no action!"]);

?>